### ISSUE TITLE
The PDF document is protected with an encryption not supported by PDFsharp.'

### ISSUE THREAD

**Issue by abodsnid** [abatsakidis/PDFDeSecure#4]
![image](https://user-images.githubusercontent.com/101536103/219876189-85d08c77-74f0-4db7-9650-964159101cbb.png)

**Comment by abatsakidis** [comment]
could you provide us with the pdf file to check the encryption

**Comment by abodsnid** [comment]
sure [but its 300 mb file ](https://easyupload.io/ogusm1)

**Comment by abodsnid** [comment]
sorry for the late answer

**Comment by qinlili23333** [comment]
Should be fixed in #6 , but file expired cannot test
