### ISSUE TITLE
example pdf works well. the program throw an exception when process the file below.

### ISSUE THREAD

**Issue by inlearn** [abatsakidis/PDFDeSecure#5]
PdfSharp.Pdf.IO.PdfReaderException:“Cannot handle iref streams. The current implementation of PDFsharp cannot handle this PDF feature introduced with Acrobat 6.”

here is the pdf file。
[初中信息科技.pdf](https://github.com/abatsakidis/PDFDeSecure/files/12829820/default.pdf)

i am a teacher, this is my textbook.  maybe this pdf is not supported by PDFsharp.

**Comment by qinlili23333** [comment]
Fixed in #6 , can be closed now
